name: Load test on Preview Environment

on:
  workflow_run:
    workflows: ['Preview Environment']
    types:
      - completed

jobs:
  Load-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - name: Install modules
        run: npm i
      - name: Install artillery
        run: npm i -g artillery
      - name: Run load tests
        run: artillery run ./loadTest.yml -t https://poc-nestjs-on-vercel-1el0et97x-tiagorosadacostas-projects.vercel.app/
