name: Load test on Preview Environment

on:
  workflow_run:
    workflows: ['Preview Environment']
    types:
      - completed

jobs:
  Load-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - name: Download environment variables artifact
        uses: actions/download-artifact@v4
        with:
          name: env-vars
          path: env-vars.txt
      - name: Install modules
        run: npm i
      - name: Install artillery
        run: npm i -g artillery
      - name: Run load tests
        run: |
          source env-vars.txt
          artillery run ./loadTest.yml -t $URL_PREVIEW
