name: Preview Environment

env:
  VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    branches:
      - master
      - stage
      - develop

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - name: Install modules
        run: npm i
      - name: Build project to deploy
        run: npm run build
      - name: Install vercel cli
        run: npm i -g vercel
      - name: Create vercel configuration
        run: |
          mkdir .vercel && \
          echo '{"projectId":"${{ secrets.VERCEL_PROJECT_ID }}","orgId":"${{ secrets.VERCEL_ORG_ID }}"}' > .vercel/project.json
      - name: Deploy preview
        run: echo $(vercel deploy --token ${{ secrets.VERCEL_ACCESS_TOKEN }} --yes) > ./output.txt && cat ./output.txt
